// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD87zgfnn4LDJIriwx_wQlo_dvgPFaVOL8',
    appId: '1:536726185629:web:76df36e9ce55187dd65674',
    messagingSenderId: '536726185629',
    projectId: 'my-iot-sem',
    authDomain: 'my-iot-sem.firebaseapp.com',
    databaseURL: 'https://my-iot-sem-default-rtdb.firebaseio.com',
    storageBucket: 'my-iot-sem.appspot.com',
    measurementId: 'G-RN709VSFPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJp2Qe7TkK-593-qIS-9jKmfDzGsiV0QY',
    appId: '1:536726185629:android:8112bc9610b4a5c1d65674',
    messagingSenderId: '536726185629',
    projectId: 'my-iot-sem',
    databaseURL: 'https://my-iot-sem-default-rtdb.firebaseio.com',
    storageBucket: 'my-iot-sem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHMEqk9qhMR6Z6pPEO84R2LqrJl3LLyX4',
    appId: '1:536726185629:ios:c47a7fb27b46223dd65674',
    messagingSenderId: '536726185629',
    projectId: 'my-iot-sem',
    databaseURL: 'https://my-iot-sem-default-rtdb.firebaseio.com',
    storageBucket: 'my-iot-sem.appspot.com',
    iosBundleId: 'com.example.smartEnergyManagmentMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHMEqk9qhMR6Z6pPEO84R2LqrJl3LLyX4',
    appId: '1:536726185629:ios:c47a7fb27b46223dd65674',
    messagingSenderId: '536726185629',
    projectId: 'my-iot-sem',
    databaseURL: 'https://my-iot-sem-default-rtdb.firebaseio.com',
    storageBucket: 'my-iot-sem.appspot.com',
    iosBundleId: 'com.example.smartEnergyManagmentMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD87zgfnn4LDJIriwx_wQlo_dvgPFaVOL8',
    appId: '1:536726185629:web:cb06caf6588bb086d65674',
    messagingSenderId: '536726185629',
    projectId: 'my-iot-sem',
    authDomain: 'my-iot-sem.firebaseapp.com',
    databaseURL: 'https://my-iot-sem-default-rtdb.firebaseio.com',
    storageBucket: 'my-iot-sem.appspot.com',
    measurementId: 'G-ZDCQKK3454',
  );

}